export const setDataList = (list, columnNumber) => {
    let min = _.min(list.map((a) => Number(a.pointString.split(",")[0])));
    let data = list.map((a) => {
      return {
        value: `${a.resultType}`,
        x: Number(a.pointString.split(",")[0]) - min,
        y: a.pointString.split(",")[1],
        issue: a?.issue,
        bg: a?.bg
      };
    });
    let result = data.reduce((sum, item) => {
      if (!sum[item.x]) sum[item.x] = Array(6).fill("");
      sum[item.x][item.y] = {
        value: item.value.replace("1", "blue").replace("2", "red"),
        issue: item.issue,
        bg: item.bg
      };
      return sum;
    }, []);
    let res = exchangeArray(result.concat(Array(_.max([0, (columnNumber || 20) - result.length])).fill(Array(6).fill(""))));
    return res;
  };
  
  const exchangeArray = (arr) => {
    let newArray = [];
    arr.forEach((item, index) => {
      item.forEach((item, iindex) => {
        if (!newArray[iindex]) newArray[iindex] = [];
        newArray[iindex][index] = item;
      });
    });
    return newArray;
  };


  export const goodWayList = {
    changlong: setDataList([
        {resultType: 1, pointString: '0,0'},
        {resultType: 1, pointString: '0,1'},
        {resultType: 1, pointString: '0,2'},
        {resultType: 2, pointString: '1,0'},
        {resultType: 2, pointString: '1,1'},
        {resultType: 2, pointString: '1,2'},
        {resultType: 1, pointString: '2,0'},
        {resultType: 1, pointString: '2,1'},
        {resultType: 2, pointString: '3,0'},
        {resultType: 2, pointString: '3,1'},
        {resultType: 1, pointString: '4,0'},
        {resultType: 1, pointString: '4,1'},
        {resultType: 1, pointString: '4,2'},
        {resultType: 1, pointString: '4,3'},
        {resultType: 2, pointString: '5,0'},
        {resultType: 2, pointString: '5,1'},
        {resultType: 2, pointString: '5,2'},
        {resultType: 1, pointString: '6,0'},
        {resultType: 1, pointString: '6,1'},
        {resultType: 2, pointString: '7,0'},
        {resultType: 2, pointString: '7,1'},
        {resultType: 2, pointString: '7,2'},
        {resultType: 1, pointString: '8,0'},
        {resultType: 1, pointString: '8,1'},
        {resultType: 1, pointString: '8,2'},
        {resultType: 2, pointString: '9,0'},
        {resultType: 2, pointString: '9,1'},
        {resultType: 1, pointString: '10,0'},
        {resultType: 1, pointString: '10,1'},
        {resultType: 1, pointString: '10,2'},
        {resultType: 2, pointString: '11,0'},
        {resultType: 2, pointString: '11,1'},
        {resultType: 1, pointString: '12,0'},
        {resultType: 1, pointString: '12,1'},
        {resultType: 2, pointString: '13,0'},
        {resultType: 2, pointString: '13,1'},
        {resultType: 2, pointString: '13,2'},
        {resultType: 1, pointString: '14,0'},
        {resultType: 1, pointString: '14,1'},
        {resultType: 2, pointString: '15,0'},
        {resultType: 2, pointString: '15,1'},
        {resultType: 2, pointString: '15,2'},
        {resultType: 2, pointString: '15,3'},
        {resultType: 1, pointString: '16,0'},
        {resultType: 1, pointString: '16,1'},
        {resultType: 2, pointString: '17,0'},
        {resultType: 2, pointString: '17,1'},
        {resultType: 2, pointString: '17,2'},
        {resultType: 1, pointString: '18,0', bg: true},
        {resultType: 1, pointString: '18,1', bg: true},
        {resultType: 1, pointString: '18,2', bg: true},
        {resultType: 1, pointString: '18,3', bg: true},
        {resultType: 1, pointString: '18,4', bg: true},
    ], 19),
    dantiao: setDataList([
        {resultType: 1, pointString: '0,0'},
        {resultType: 1, pointString: '0,1'},
        {resultType: 1, pointString: '0,2'},
        {resultType: 2, pointString: '1,0'},
        {resultType: 2, pointString: '1,1'},
        {resultType: 2, pointString: '1,2'},
        {resultType: 1, pointString: '2,0'},
        {resultType: 1, pointString: '2,1'},
        {resultType: 2, pointString: '3,0'},
        {resultType: 2, pointString: '3,1'},
        {resultType: 1, pointString: '4,0'},
        {resultType: 1, pointString: '4,1'},
        {resultType: 1, pointString: '4,2'},
        {resultType: 1, pointString: '4,3'},
        {resultType: 2, pointString: '5,0'},
        {resultType: 2, pointString: '5,1'},
        {resultType: 2, pointString: '5,2'},
        {resultType: 1, pointString: '6,0'},
        {resultType: 1, pointString: '6,1'},
        {resultType: 2, pointString: '7,0'},
        {resultType: 2, pointString: '7,1'},
        {resultType: 2, pointString: '7,2'},
        {resultType: 1, pointString: '8,0'},
        {resultType: 1, pointString: '8,1'},
        {resultType: 1, pointString: '8,2'},
        {resultType: 2, pointString: '9,0'},
        {resultType: 2, pointString: '9,1'},
        {resultType: 1, pointString: '10,0'},
        {resultType: 1, pointString: '10,1'},
        {resultType: 1, pointString: '10,2'},
        {resultType: 2, pointString: '11,0'},
        {resultType: 2, pointString: '11,1'},
        {resultType: 1, pointString: '12,0'},
        {resultType: 1, pointString: '12,1'},
        {resultType: 2, pointString: '13,0'},
        {resultType: 2, pointString: '13,1'},
        {resultType: 2, pointString: '13,2'},
        {resultType: 1, pointString: '14,0', bg: true},
        {resultType: 2, pointString: '15,0', bg: true},
        {resultType: 1, pointString: '16,0', bg: true},
        {resultType: 2, pointString: '17,0', bg: true},
        {resultType: 1, pointString: '18,0', bg: true},
    ],19),
    lflt: setDataList([
        {resultType: 1, pointString: '0,0'},
        {resultType: 1, pointString: '0,1'},
        {resultType: 1, pointString: '0,2'},
        {resultType: 2, pointString: '1,0'},
        {resultType: 2, pointString: '1,1'},
        {resultType: 2, pointString: '1,2'},
        {resultType: 1, pointString: '2,0'},
        {resultType: 1, pointString: '2,1'},
        {resultType: 2, pointString: '3,0'},
        {resultType: 2, pointString: '3,1'},
        {resultType: 1, pointString: '4,0'},
        {resultType: 1, pointString: '4,1'},
        {resultType: 1, pointString: '4,2'},
        {resultType: 1, pointString: '4,3'},
        {resultType: 2, pointString: '5,0'},
        {resultType: 2, pointString: '5,1'},
        {resultType: 2, pointString: '5,2'},
        {resultType: 1, pointString: '6,0'},
        {resultType: 1, pointString: '6,1'},
        {resultType: 2, pointString: '7,0'},
        {resultType: 2, pointString: '7,1'},
        {resultType: 2, pointString: '7,2'},
        {resultType: 1, pointString: '8,0'},
        {resultType: 1, pointString: '8,1'},
        {resultType: 1, pointString: '8,2'},
        {resultType: 2, pointString: '9,0'},
        {resultType: 2, pointString: '9,1'},
        {resultType: 1, pointString: '10,0'},
        {resultType: 1, pointString: '10,1'},
        {resultType: 1, pointString: '10,2'},
        {resultType: 2, pointString: '11,0'},
        {resultType: 2, pointString: '11,1'},
        {resultType: 1, pointString: '12,0'},
        {resultType: 1, pointString: '12,1'},
        {resultType: 2, pointString: '13,0'},
        {resultType: 2, pointString: '13,1'},
        {resultType: 2, pointString: '13,2'},
        {resultType: 1, pointString: '14,0'},
        {resultType: 1, pointString: '14,1'},
        {resultType: 1, pointString: '14,2'},
        {resultType: 2, pointString: '15,0'},
        {resultType: 2, pointString: '15,1'},
        {resultType: 2, pointString: '15,2'},
        {resultType: 2, pointString: '15,3'},
        {resultType: 1, pointString: '16,0', bg: true},
        {resultType: 1, pointString: '16,1', bg: true},
        {resultType: 2, pointString: '17,0', bg: true},
        {resultType: 2, pointString: '17,1', bg: true},
        {resultType: 1, pointString: '18,0', bg: true},
        {resultType: 1, pointString: '18,1', bg: true},
    ],19),
    lfyt: setDataList([
        {resultType: 1, pointString: '0,0'},
        {resultType: 1, pointString: '0,1'},
        {resultType: 1, pointString: '0,2'},
        {resultType: 2, pointString: '1,0'},
        {resultType: 2, pointString: '1,1'},
        {resultType: 2, pointString: '1,2'},
        {resultType: 1, pointString: '2,0'},
        {resultType: 1, pointString: '2,1'},
        {resultType: 2, pointString: '3,0'},
        {resultType: 2, pointString: '3,1'},
        {resultType: 1, pointString: '4,0'},
        {resultType: 1, pointString: '4,1'},
        {resultType: 1, pointString: '4,2'},
        {resultType: 1, pointString: '4,3'},
        {resultType: 2, pointString: '5,0'},
        {resultType: 2, pointString: '5,1'},
        {resultType: 2, pointString: '5,2'},
        {resultType: 1, pointString: '6,0'},
        {resultType: 1, pointString: '6,1'},
        {resultType: 2, pointString: '7,0'},
        {resultType: 2, pointString: '7,1'},
        {resultType: 2, pointString: '7,2'},
        {resultType: 1, pointString: '8,0'},
        {resultType: 1, pointString: '8,1'},
        {resultType: 1, pointString: '8,2'},
        {resultType: 2, pointString: '9,0'},
        {resultType: 2, pointString: '9,1'},
        {resultType: 1, pointString: '10,0'},
        {resultType: 1, pointString: '10,1'},
        {resultType: 1, pointString: '10,2'},
        {resultType: 2, pointString: '11,0'},
        {resultType: 2, pointString: '11,1'},
        {resultType: 1, pointString: '12,0'},
        {resultType: 1, pointString: '12,1'},
        {resultType: 1, pointString: '12,2'},
        {resultType: 1, pointString: '12,3'},
        {resultType: 2, pointString: '13,0'},
        {resultType: 1, pointString: '14,0', bg: true},
        {resultType: 1, pointString: '14,1', bg: true},
        {resultType: 2, pointString: '15,0', bg: true},
        {resultType: 1, pointString: '16,0', bg: true},
        {resultType: 1, pointString: '16,1', bg: true},
        {resultType: 2, pointString: '17,0', bg: true},
        {resultType: 1, pointString: '18,0', bg: true},
        {resultType: 1, pointString: '18,1', bg: true},
    ],19),
    lxcl: setDataList([
        {resultType: 1, pointString: '0,0'},
        {resultType: 1, pointString: '0,1'},
        {resultType: 1, pointString: '0,2'},
        {resultType: 2, pointString: '1,0'},
        {resultType: 2, pointString: '1,1'},
        {resultType: 2, pointString: '1,2'},
        {resultType: 1, pointString: '2,0'},
        {resultType: 1, pointString: '2,1'},
        {resultType: 2, pointString: '3,0'},
        {resultType: 2, pointString: '3,1'},
        {resultType: 1, pointString: '4,0'},
        {resultType: 1, pointString: '4,1'},
        {resultType: 1, pointString: '4,2'},
        {resultType: 1, pointString: '4,3'},
        {resultType: 2, pointString: '5,0'},
        {resultType: 2, pointString: '5,1'},
        {resultType: 2, pointString: '5,2'},
        {resultType: 1, pointString: '6,0'},
        {resultType: 1, pointString: '6,1'},
        {resultType: 2, pointString: '7,0'},
        {resultType: 2, pointString: '7,1'},
        {resultType: 2, pointString: '7,2'},
        {resultType: 1, pointString: '8,0'},
        {resultType: 1, pointString: '8,1'},
        {resultType: 1, pointString: '8,2'},
        {resultType: 2, pointString: '9,0'},
        {resultType: 2, pointString: '9,1'},
        {resultType: 1, pointString: '10,0'},
        {resultType: 1, pointString: '10,1'},
        {resultType: 1, pointString: '10,2'},
        {resultType: 2, pointString: '11,0'},
        {resultType: 2, pointString: '11,1'},
        {resultType: 1, pointString: '12,0'},
        {resultType: 1, pointString: '12,1'},
        {resultType: 1, pointString: '12,2'},
        {resultType: 1, pointString: '12,3'},
        {resultType: 2, pointString: '13,0'},
        {resultType: 2, pointString: '13,1'},
        {resultType: 1, pointString: '14,0'},
        {resultType: 2, pointString: '15,0', bg: true},
        {resultType: 2, pointString: '15,1', bg: true},
        {resultType: 2, pointString: '15,2', bg: true},
        {resultType: 2, pointString: '15,3', bg: true},
        {resultType: 2, pointString: '15,4', bg: true},
        {resultType: 1, pointString: '16,0', bg: true},
        {resultType: 1, pointString: '16,1', bg: true},
        {resultType: 1, pointString: '16,2', bg: true},
        {resultType: 2, pointString: '17,0', bg: true},
        {resultType: 2, pointString: '17,1', bg: true},
        {resultType: 1, pointString: '18,0', bg: true},
        {resultType: 1, pointString: '18,1', bg: true},
    ],19),
    buguosan: setDataList([
        {resultType: 1, pointString: '0,0'},
        {resultType: 1, pointString: '0,1'},
        {resultType: 1, pointString: '0,2'},
        {resultType: 2, pointString: '1,0'},
        {resultType: 2, pointString: '1,1'},
        {resultType: 2, pointString: '1,2'},
        {resultType: 1, pointString: '2,0'},
        {resultType: 1, pointString: '2,1'},
        {resultType: 2, pointString: '3,0'},
        {resultType: 2, pointString: '3,1'},
        {resultType: 2, pointString: '3,2'},
        {resultType: 2, pointString: '3,3'},
        {resultType: 2, pointString: '3,4'},
        {resultType: 1, pointString: '4,0', bg: true},
        {resultType: 1, pointString: '4,1', bg: true},
        {resultType: 1, pointString: '4,2', bg: true},
        {resultType: 2, pointString: '5,0', bg: true},
        {resultType: 2, pointString: '5,1', bg: true},
        {resultType: 2, pointString: '5,2', bg: true},
        {resultType: 1, pointString: '6,0', bg: true},
        {resultType: 1, pointString: '6,1', bg: true},
        {resultType: 2, pointString: '7,0', bg: true},
        {resultType: 2, pointString: '7,1', bg: true},
        {resultType: 2, pointString: '7,2', bg: true},
        {resultType: 1, pointString: '8,0', bg: true},
        {resultType: 1, pointString: '8,1', bg: true},
        {resultType: 1, pointString: '8,2', bg: true},
        {resultType: 2, pointString: '9,0', bg: true},
        {resultType: 2, pointString: '9,1', bg: true},
        {resultType: 1, pointString: '10,0', bg: true},
        {resultType: 1, pointString: '10,1', bg: true},
        {resultType: 1, pointString: '10,2', bg: true},
        {resultType: 2, pointString: '11,0', bg: true},
        {resultType: 2, pointString: '11,1', bg: true},
        {resultType: 1, pointString: '12,0', bg: true},
        {resultType: 1, pointString: '12,1', bg: true},
        {resultType: 1, pointString: '12,2', bg: true},
        {resultType: 2, pointString: '13,0', bg: true},
        {resultType: 2, pointString: '13,1', bg: true},
        {resultType: 1, pointString: '14,0', bg: true},
        {resultType: 2, pointString: '15,0', bg: true},
        {resultType: 2, pointString: '15,1', bg: true},
        {resultType: 2, pointString: '15,2', bg: true},
        {resultType: 1, pointString: '16,0', bg: true},
        {resultType: 1, pointString: '16,1', bg: true},
        {resultType: 1, pointString: '16,2', bg: true},
        {resultType: 2, pointString: '17,0', bg: true},
        {resultType: 2, pointString: '17,1', bg: true},
        {resultType: 1, pointString: '18,0', bg: true},
        {resultType: 1, pointString: '18,1', bg: true},
    ],19),
    changlian: setDataList([
        {resultType: 2, pointString: '0,0'},
        {resultType: 2, pointString: '0,1'},
        {resultType: 2, pointString: '0,2'},
        {resultType: 1, pointString: '1,0'},
        {resultType: 1, pointString: '1,1'},
        {resultType: 1, pointString: '1,2'},
        {resultType: 2, pointString: '2,0'},
        {resultType: 2, pointString: '2,1'},
        {resultType: 1, pointString: '3,0'},
        {resultType: 1, pointString: '3,1'},
        {resultType: 1, pointString: '3,2'},
        {resultType: 1, pointString: '3,3'},
        {resultType: 2, pointString: '4,0', bg: true},
        {resultType: 2, pointString: '4,1', bg: true},
        {resultType: 1, pointString: '5,0'},
        {resultType: 1, pointString: '5,1'},
        {resultType: 1, pointString: '5,2'},
        {resultType: 2, pointString: '6,0', bg: true},
        {resultType: 2, pointString: '6,1', bg: true},
        {resultType: 1, pointString: '7,0'},
        {resultType: 1, pointString: '7,1'},
        {resultType: 2, pointString: '8,0', bg: true},
        {resultType: 2, pointString: '8,1', bg: true},
        {resultType: 1, pointString: '9,0'},
        {resultType: 1, pointString: '9,1'},
        {resultType: 1, pointString: '9,2'},
        {resultType: 2, pointString: '10,0', bg: true},
        {resultType: 2, pointString: '10,1', bg: true},
        {resultType: 1, pointString: '11,0'},
        {resultType: 2, pointString: '12,0', bg: true},
        {resultType: 2, pointString: '12,1', bg: true},
        {resultType: 1, pointString: '13,0'},
        {resultType: 2, pointString: '14,0', bg: true},
        {resultType: 2, pointString: '14,1', bg: true},
        {resultType: 1, pointString: '15,0'},
        {resultType: 2, pointString: '16,0', bg: true},
        {resultType: 2, pointString: '16,1', bg: true},
        {resultType: 1, pointString: '17,0'},
        {resultType: 1, pointString: '17,1'},
        {resultType: 1, pointString: '17,2'},
        {resultType: 1, pointString: '17,3'},
        {resultType: 2, pointString: '18,0', bg: true},
        {resultType: 2, pointString: '18,1', bg: true},
    ],19),
    changtiao: setDataList([
        {resultType: 2, pointString: '0,0'},
        {resultType: 2, pointString: '0,1'},
        {resultType: 2, pointString: '0,2'},
        {resultType: 1, pointString: '1,0'},
        {resultType: 1, pointString: '1,1'},
        {resultType: 1, pointString: '1,2'},
        {resultType: 2, pointString: '2,0'},
        {resultType: 2, pointString: '2,1'},
        {resultType: 1, pointString: '3,0'},
        {resultType: 1, pointString: '3,1'},
        {resultType: 2, pointString: '4,0', bg: true},
        {resultType: 1, pointString: '5,0'},
        {resultType: 1, pointString: '5,1'},
        {resultType: 2, pointString: '6,0', bg: true},
        {resultType: 1, pointString: '7,0'},
        {resultType: 1, pointString: '7,1'},
        {resultType: 1, pointString: '7,2'},
        {resultType: 2, pointString: '8,0', bg: true},
        {resultType: 1, pointString: '9,0'},
        {resultType: 1, pointString: '9,1'},
        {resultType: 1, pointString: '9,2'},
        {resultType: 1, pointString: '9,3'},
        {resultType: 2, pointString: '10,0', bg: true},
        {resultType: 1, pointString: '11,0'},
        {resultType: 1, pointString: '11,1'},
        {resultType: 2, pointString: '12,0', bg: true},
        {resultType: 1, pointString: '13,0'},
        {resultType: 2, pointString: '14,0', bg: true},
        {resultType: 1, pointString: '15,0'},
        {resultType: 2, pointString: '16,0', bg: true},
        {resultType: 1, pointString: '17,0'},
        {resultType: 1, pointString: '17,1'},
        {resultType: 2, pointString: '18,0', bg: true},
    ],19),
  }